
import apiService, {
  ApiResponse,
  get,
  post,
  put,
  patch,
  del,
  setToken,
  getToken,
  clearToken,
  isAuthenticated as isApiAuthenticated
} from './api';

import authService, {
  LoginCredentials,
  RegisterData,
  ChangePasswordData,
  LoginResponse,
  login,
  logout,
  getCurrentUser,
  register,
  changePassword,
  hasRole,
  isAuthenticated,
  getUserFromStorage,
  updateProfile
} from './authService';

import productService, {
  ProductFilters,
  PaginatedResponse,
  ProductInput,
  CategoryInput,
  StockUpdateInput,
  getProducts,
  getProductById,
  createProduct,
  updateProduct,
  deleteProduct,
  getProductsByCategory,
  getLowStockProducts,
  updateProductStock,
  getCategories,
  createCategory,
  updateCategory,
  deleteCategory
} from './productService';

import transactionService, {
  TransactionFilters,
  TransactionInput,
  SalesReportData,
  ProfitLossReportData,
  DashboardData as TransactionDashboardData,
  ReceiptData,
  getTransactions,
  getTransactionById,
  createTransaction,
  cancelTransaction,
  getDailySalesReport,
  getWeeklySalesReport,
  getMonthlySalesReport,
  getProfitLossReport,
  getDashboardData as getTransactionDashboardData,
  exportTransactionsToCSV,
  getTransactionReceipt,
  downloadTransactionReceipt,
  downloadTransactionsCSV
} from './transactionService';

import userService, {
  UserListParams,
  UserListResponse,
  CreateUserData,
  UpdateUserData,
  ChangePasswordData as UserChangePasswordData,
  ProfileUpdateData,
  RoleData,
  getUsers,
  getUserById,
  createUser,
  updateUser,
  deleteUser,
  toggleUserStatus,
  changeUserPassword,
  getRoles,
  getCurrentUserProfile,
  updateUserProfile
} from './userService';

import dashboardService, {
  getDashboardSummary,
  getDailySalesData,
  getCategorySalesData,
  getTopProducts,
  getLowStockProducts,
  getPaymentMethodSales,
  getAllDashboardData,
  getYearToDateComparison
} from './dashboardService';

import reportService, {
  getSalesReport,
  getProductSalesReport,
  getCategorySalesReport,
  getProfitReport,
  getInventoryReport,
  getCashierPerformanceReport,
  downloadReport,
  emailReport
} from './reportService';

import settingsService, {
  BackupParams,
  BackupListParams,
  getStoreSettings,
  updateStoreSettings,
  uploadStoreLogo,
  getAppSettings,
  updateAppSettings,
  getUserPreferences,
  updateUserPreferences,
  createBackup,
  getBackupsList,
  getBackupDetails,
  deleteBackup,
  restoreFromBackup,
  getBackupDownloadUrl,
  downloadBackup,
  getAllSettings
} from './settingsService';

import customerService, {
  CustomerListParams,
  CustomerFormData,
  CustomerSummary,
  CustomerNote,
  CustomerImportResult,
  TopCustomer,
  getCustomers,
  getCustomerById,
  createCustomer,
  updateCustomer,
  deleteCustomer,
  getCustomerTransactions,
  getCustomerSummary,
  addCustomerNote,
  getCustomerNotes,
  deleteCustomerNote,
  importCustomersFromCSV,
  exportCustomers,
  getTopCustomers
} from './customerService';

import supplierService, {
  SupplierListParams,
  SupplierFormData,
  PurchaseListParams,
  PurchaseFormData,
  PurchaseStatusUpdateData,
  getSuppliers,
  getSupplierById,
  createSupplier,
  updateSupplier,
  deleteSupplier,
  toggleSupplierStatus,
  addSupplierNote,
  getSupplierNotes,
  deleteSupplierNote,
  importSuppliersFromCSV,
  exportSuppliers,
  getSupplierPurchases,
  getPurchases,
  getPurchaseById,
  createPurchase,
  updatePurchase,
  updatePurchaseStatus,
  cancelPurchase,
  getSupplierPurchasesReport,
  downloadSupplierPurchasesReport
} from './supplierService';

// Re-export all services as individual named exports
export {
  // API Service
  apiService,
  ApiResponse,
  get,
  post,
  put,
  patch,
  del,
  setToken,
  getToken,
  clearToken,
  isApiAuthenticated,

  // Auth Service
  authService,
  LoginCredentials,
  RegisterData,
  ChangePasswordData,
  LoginResponse,
  login,
  logout,
  getCurrentUser,
  register,
  changePassword,
  hasRole,
  isAuthenticated,
  getUserFromStorage,
  updateProfile,

  // Product Service
  productService,
  ProductFilters,
  PaginatedResponse,
  ProductInput,
  CategoryInput,
  StockUpdateInput,
  getProducts,
  getProductById,
  createProduct,
  updateProduct,
  deleteProduct,
  getProductsByCategory,
  getLowStockProducts,
  updateProductStock,
  getCategories,
  createCategory,
  updateCategory,
  deleteCategory,

  // Transaction Service
  transactionService,
  TransactionFilters,
  TransactionInput,
  SalesReportData,
  ProfitLossReportData,
  TransactionDashboardData,
  ReceiptData,
  getTransactions,
  getTransactionById,
  createTransaction,
  cancelTransaction,
  getDailySalesReport,
  getWeeklySalesReport,
  getMonthlySalesReport,
  getProfitLossReport,
  getTransactionDashboardData,
  exportTransactionsToCSV,
  getTransactionReceipt,
  downloadTransactionReceipt,
  downloadTransactionsCSV,

  // User Service
  userService,
  UserListParams,
  UserListResponse,
  CreateUserData,
  UpdateUserData,
  UserChangePasswordData,
  ProfileUpdateData,
  RoleData,
  getUsers,
  getUserById,
  createUser,
  updateUser,
  deleteUser,
  toggleUserStatus,
  changeUserPassword,
  getRoles,
  getCurrentUserProfile,
  updateUserProfile,

  // Dashboard Service
  dashboardService,
  getDashboardSummary,
  getDailySalesData,
  getCategorySalesData,
  getTopProducts,
  getLowStockProducts,
  getPaymentMethodSales,
  getAllDashboardData,
  getYearToDateComparison,

  // Report Service
  reportService,
  getSalesReport,
  getProductSalesReport,
  getCategorySalesReport,
  getProfitReport,
  getInventoryReport,
  getCashierPerformanceReport,
  downloadReport,
  emailReport,

  // Settings Service
  settingsService,
  BackupParams,
  BackupListParams,
  getStoreSettings,
  updateStoreSettings,
  uploadStoreLogo,
  getAppSettings,
  updateAppSettings,
  getUserPreferences,
  updateUserPreferences,
  createBackup,
  getBackupsList,
  getBackupDetails,
  deleteBackup,
  restoreFromBackup,
  getBackupDownloadUrl,
  downloadBackup,
  getAllSettings,

  // Customer Service
  customerService,
  CustomerListParams,
  CustomerFormData,
  CustomerSummary,
  CustomerNote,
  CustomerImportResult,
  TopCustomer,
  getCustomers,
  getCustomerById,
  createCustomer,
  updateCustomer,
  deleteCustomer,
  getCustomerTransactions,
  getCustomerSummary,
  addCustomerNote,
  getCustomerNotes,
  deleteCustomerNote,
  importCustomersFromCSV,
  exportCustomers,
  getTopCustomers,

  // Supplier Service
  supplierService,
  SupplierListParams,
  SupplierFormData,
  PurchaseListParams,
  PurchaseFormData,
  PurchaseStatusUpdateData,
  getSuppliers,
  getSupplierById,
  createSupplier,
  updateSupplier,
  deleteSupplier,
  toggleSupplierStatus,
  addSupplierNote,
  getSupplierNotes,
  deleteSupplierNote,
  importSuppliersFromCSV,
  exportSuppliers,
  getSupplierPurchases,
  getPurchases,
  getPurchaseById,
  createPurchase,
  updatePurchase,
  updatePurchaseStatus,
  cancelPurchase,
  getSupplierPurchasesReport,
  downloadSupplierPurchasesReport
};

// Create a consolidated services object for default export
const services = {
  api: apiService,
  auth: authService,
  product: productService,
  transaction: transactionService,
  user: userService,
  dashboard: dashboardService,
  report: reportService,
  settings: settingsService,
  customer: customerService,
  supplier: supplierService
};

// Default export for importing all services at once
export default services;
